name: Nix formatting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  nix-fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            persist-credentials: false

      - name: Set up git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull

      - name: Nix cache
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Format with nix fmt
        run: |
          nix fmt
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Formatting"
            git push
          fi

